# Aanbevelingen

Het draaien van een stochastenanalyse met het CM-model als zodanig was een bijzonder taaie klus. In de eerste plaats vooral vanwege het gesloten karakter van dit model. Voor een hydroloog is dit model feitelijk een 'black box' waaraan via .mat-bestanden tijdreeksen moeten worden opgedrukt, in de hoop dat de juiste tijdreeks met de juiste eenheden en de juiste tijdstapgrootte zijn opgegeven in de juiste kolom van het invoerbestand. Sumaqua zou modelschematisaties van dit type een enorme boost kunnen geven als de modelinput en -output opgenomen zouden worden in een goede GUI (Graphical User Interface) met topografische kaart en daarop geplot de gebieden/polygonen die in het model vertegenwoordigd zijn.

Een ander verbeterpunt van het CM-model van 's-Hertogenbosch betreft het feit dat de initiële volumes van polygonen 22 en 24 niet nul mogen zijn. Dit ontdekten we gedurende het project omdat het model bij die instellingen crashte.

Tot slot zou het CM-model een heel stuk gebruiksvriendelijker worden voor stochastenanalyses als de input voor beekinstroom en lateralen (Q) zou worden losgetrokken van de input voor waterhoogtes (H). Doordat de beekinstroom en de maaswaterstanden in één en hetzelfde invoerbestand moesten worden weggeschreven waren we gedwongen om al op voorhand alle combinaties te bouwen van de bijbehorende stochasten. Anders gezegd: [De Nieuwe Stochastentool](https://github.com/SiebeBosch/DeNieuweStochastentool) kon niet goed tot zijn recht komen omdat het niet de kans kreeg zelf de combinaties van beekinstroom en maaswaterstand op te stellen.

De simulaties zonder laterale instromingen resulteren in sommige locaties, zelfs ver bovenstrooms in de Beneden-Aa in **hogere** waterstanden dan met laterale instromingen. Dit is volkomen contra-intuïtief. Wij hebben daarom meermaals de invoer gecheckt maar blijven op deze resultaten uitkomen. Aanbeveling is daarom dat Waterschap Aa en Maas nader onderzoekt wat de oorzaak hiervan is.

Tot slot hebben we, op last van de opdrachtgever, in dit project de aanname gedaan dat de stochasten maaswaterstand en beekinstroom statistisch onafhankelijk zijn. Deze aanname is in dit project acceptabel omdat het hier niet ging om de absolute overschrijdingswaterstanden maar om een gevoeligheidsanalyse. Voor toekomstige daadwerkelijke stochastenanalyses is het echter raadzaam om expliciet rekening te houden met de afhankelijkheid tussen beide stochasten.








Op de beoordelingslocatie ADM Bossche Broek is het effect van het wel of niet meenemen van laterale instromingen of een verhoogde initiële vullingsgraad van het model verwaarloosbaar. Het effect op de overschrijdingswaterstanden ligt in de orde grootte van slechts enkele millimeters.

Een nuance hierbij is op zijn plaats: in geen van de simulaties is het peil waarboven het bergingsgebied Bossche Broek wordt ingezet, 4.90 m + NAP, gehaald.

Locaties waar het effect wél significant is, betreffen vooral de knopen in de polder achter het Segersgemaal. Bij ontbreken van laterale instromingen vinden in de polder geen peilstijgingen plaats en treedt het gemaal niet in werking.






