name: blokkendoos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - gdal=3.6.2
  - rasterio=1.3.6
  - fiona=1.9.1
  - pyproj=3.5.0
  - geopandas=0.13.2
  - shapely=2.0.1
  - numpy=1.24.3
  - pip
  - pip:
    - pysheds>=0.2.7